"""Add type_id column to blueprint

Revision ID: 234b9dc146dc
Revises: 
Create Date: 2025-06-10 16:18:56.999671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234b9dc146dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.alter_column('region_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'10000002'"))
        batch_op.alter_column('station_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('use_region_orders',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.alter_column('use_region_orders',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('station_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('region_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'10000002'"))
        batch_op.drop_column('type_id')

    # ### end Alembic commands ###
