"""added fallback check to blueprints.

Revision ID: 5b7de2b5e975
Revises: 8cd1d3a97648
Create Date: 2025-06-12 07:00:06.161528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7de2b5e975'
down_revision = '8cd1d3a97648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_jita_fallback', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.drop_column('used_jita_fallback')

    # ### end Alembic commands ###
