"""removed region_id from BP, added use_jita_sell

Revision ID: cd1d8a30b7e2
Revises: fe9440f27c05
Create Date: 2025-06-11 17:50:11.070918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1d8a30b7e2'
down_revision = 'fe9440f27c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_jita_sell', sa.Boolean(), nullable=True))
        batch_op.drop_column('region_id')
        batch_op.drop_column('use_region_orders')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_region_orders', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('region_id', sa.INTEGER(), server_default=sa.text("'10000002'"), nullable=True))
        batch_op.drop_column('use_jita_sell')

    # ### end Alembic commands ###
