"""Add type_id to blueprints and sell_price to materials

Revision ID: fe9440f27c05
Revises: dcdd956fc694
Create Date: 2025-06-11 17:07:56.783108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9440f27c05'
down_revision = 'dcdd956fc694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sell_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('sell_price')

    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.drop_column('type_id')

    # ### end Alembic commands ###
