"""Added runs per copy

Revision ID: 7859b1f6fda2
Revises: 733251a602d2
Create Date: 2025-05-30 14:00:17.043325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7859b1f6fda2'
down_revision = '733251a602d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint_t2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('runs_per_copy', sa.Integer(), server_default='10', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint_t2', schema=None) as batch_op:
        batch_op.drop_column('runs_per_copy')

    # ### end Alembic commands ###
