"""Add Invention Cost

Revision ID: c36fa1db0bea
Revises: 11ca30d8b93a
Create Date: 2025-05-24 13:21:47.158420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c36fa1db0bea'
down_revision = '11ca30d8b93a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint_t2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invention_cost', sa.Float(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint_t2', schema=None) as batch_op:
        batch_op.drop_column('invention_cost')

    # ### end Alembic commands ###
