"""Add type_id and category to materials.

Revision ID: 5290191a5dda
Revises: e93f8b66f0fc
Create Date: 2025-06-10 21:18:46.112209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5290191a5dda'
down_revision = 'e93f8b66f0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.drop_column('type_id')

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('type_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
