"""defaulting region id to jitas

Revision ID: 530471008cb9
Revises: c51a081ad3f9
Create Date: 2025-06-11 18:50:03.837283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530471008cb9'
down_revision = 'c51a081ad3f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_id', sa.Integer(), nullable=False, server_default='10000002'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_id', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.drop_column('region_id')

    # ### end Alembic commands ###
