"""defaulting use_jita_sell to true

Revision ID: 7e4454ee0edf
Revises: cd1d8a30b7e2
Create Date: 2025-06-11 18:04:29.291357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '7e4454ee0edf'
down_revision = 'cd1d8a30b7e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint') as batch_op:
        batch_op.add_column(
            sa.Column('use_jita_sell', sa.Boolean(), nullable=False, server_default=sa.true())
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.drop_column('use_jita_sell')

    op.create_table('_alembic_tmp_blueprint',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('materials', sqlite.JSON(), nullable=False),
    sa.Column('sell_price', sa.FLOAT(), nullable=False),
    sa.Column('max', sa.INTEGER(), nullable=True),
    sa.Column('material_cost', sa.FLOAT(), nullable=False),
    sa.Column('tier', sa.VARCHAR(length=10), server_default=sa.text("'T1'"), nullable=False),
    sa.Column('station_id', sa.INTEGER(), nullable=True),
    sa.Column('type_id', sa.INTEGER(), nullable=True),
    sa.Column('use_jita_sell', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
