"""Added relationship between station_IDs

Revision ID: 8cd1d3a97648
Revises: 530471008cb9
Create Date: 2025-06-12 04:03:30.088850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd1d3a97648'
down_revision = '530471008cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_blueprint_station_id', 'station', ['station_id'], ['station_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.drop_constraint('fk_blueprint_station_id', type_='foreignkey')

    # ### end Alembic commands ###
