"""added back region_id to bp and removed it from station

Revision ID: c51a081ad3f9
Revises: 7e4454ee0edf
Create Date: 2025-06-11 18:48:15.109267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51a081ad3f9'
down_revision = '7e4454ee0edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.drop_column('region_id')

    # ### end Alembic commands ###
