"""Add type_id column to materials

Revision ID: e93f8b66f0fc
Revises: 234b9dc146dc
Create Date: 2025-06-10 16:24:42.438603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93f8b66f0fc'
down_revision = '234b9dc146dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('type_id')

    # ### end Alembic commands ###
