"""Rename type to tier in blueprint

Revision ID: 11ca30d8b93a
Revises: 843078787a16
Create Date: 2025-05-24 11:55:58.674053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ca30d8b93a'
down_revision = '843078787a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.alter_column('type', new_column_name='tier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=10), server_default=sa.text("'T1'"), nullable=False))
        batch_op.drop_column('tier')

    # ### end Alembic commands ###
