"""Add T2 blueprint support

Revision ID: 843078787a16
Revises: 
Create Date: 2025-05-24 11:23:41.912697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843078787a16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blueprint_t2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invention_chance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['blueprint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=10), nullable=False, server_default='T1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.drop_column('type')

    op.drop_table('blueprint_t2')
    # ### end Alembic commands ###
